# Generated by Django 5.2.17 on 2026-09-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='admin_only_chat',
            field=models.BooleanField(default=False, help_text="If true, only project admins may post in this project's group chat."),
        ),
    ]
