# Generated by Django 5.2.17 on 2026-08-13 04:01

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.direct_attachment_upload_path, validators=[chat.models._validate_chat_attachment_size]),
        ),
        migrations.AddField(
            model_name='projectmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.project_attachment_upload_path, validators=[chat.models._validate_chat_attachment_size]),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectmessage',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
