# Generated by Django 5.2.17 on 2026-09-02 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_directmessage_attachment_projectmessage_attachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmessage',
            name='hidden_for',
            field=models.ManyToManyField(blank=True, related_name='hidden_project_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
