# Generated by Django 5.2.17 on 2026-08-08 08:36

import django.db.models.deletion
import submissions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=submissions.models.submission_upload_path, validators=[submissions.models.validate_file_size])),
                ('repo_link', models.URLField(blank=True, help_text='e.g. GitHub repository URL')),
                ('live_link', models.URLField(blank=True, help_text='Optional live/deployed demo URL')),
                ('description', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='projects.project')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('project', 'member')},
            },
        ),
    ]
