# Generated by Django 5.2.17 on 2026-08-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('task_assigned', 'Assigned to a task'), ('project_message', 'New project chat message'), ('direct_message', 'New direct message')], max_length=30),
        ),
    ]
