# Generated by Django 5.2.17 on 2026-08-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('task_assigned', 'Assigned to a task'), ('project_message', 'New project chat message'), ('direct_message', 'New direct message'), ('member_added', 'Added to a project')], max_length=30),
        ),
    ]
